version: "3.9"

services:
  web:
    build: .
    container_name: django_app_cicd
    command: >
      sh -c "python manage.py migrate &&
                   pytest --maxfail=1 --disable-warnings -q &&
                   python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app

